# Describes the format for available aftership services

handle_update_channels:
  name: update_channels
  description: update_channels.
  fields:
    file:
      name: config_entry
      description: the name of file that contains the channel
      required: true

      selector:
        config_entry:
          filter:
            integration: "epg"



