# Describes the format for available aftership services

track_channel:
  name: track_channel
  description: Add new Channel.
  fields:
    channel_id:
      name: channel_id
      description: Id of channel as apper in sensor.epg_{filename} Attributes
      required: true
      example: "Eurosport"
      selector:
        text:



remove_channel:
  name: remove_channel
  description: Remove Channel.
  fields:
    channel_id:
      name: channel_id
      description: Id of channel as apper in sensor.epg_{filename} Attributes
      required: true
      example: "Eurosport"
      selector:
        text:
