handle_update_channels:
  name: update_channels
  description: Force update Guide file
  fields:
    entry_id:
      name: config_entry
      description: The ID of the config_entry to update
      required: true
      selector:
        config_entry:
          integration: "epg"







